CREATE TABLE IF NOT EXISTS Company
(ID INTEGER NOT NULL AUTO_INCREMENT,
 Director_ID INTEGER,
 Name VARCHAR(255),
 FocusArea VARCHAR(255),
 PRIMARY KEY (ID)
);
 
CREATE TABLE IF NOT EXISTS Filial
(ID INTEGER NOT NULL AUTO_INCREMENT,
 Company_ID INTEGER,
 Name VARCHAR(255),
 PRIMARY KEY (ID),
 FOREIGN KEY (Company_ID) REFERENCES Company(ID)
 );